import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'

export default function Home() {

  const navigation = [
    {

    }
  ]
  return (
    <div className="">
      <Head>
        <title>Sunny Side Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <div className=''>
        <Navbar />
        {/* <Image className='md:sr-only lg:sr-only xl:sr-only' src="/static/images/mobile/image-header.jpg" alt="sun" layout='responsive' width={600} height={650} /> */}
        <div className='aspect-w-16 aspect-h-9'>
          <Image className=' ' src="/static/images/desktop/image-header.jpg" alt="sun" layout='responsive' width='1240' height='450' />
          <Image className='aspec' src='/static/images/desktop/image-transform.jpg' alt='egg' width='1240'  height="340" />
        </div>
      </div>


    {/* end of first div */}
    </div>
  )
}
